### ISSUE TITLE
Some evaluations not working as expected.

### ISSUE THREAD

**Issue by kartavya-ramnani** [nikunjy/rules#10]
The documentation is not very clear and this is what I have done and it is not really working.

```
m := make(map[string]interface{})

m["bankcode"] = "CIT"

rule := "bankcode eq CIT"

fmt.Println("Rule Passed ? : ", parser.Evaluate(rule,m))

```

output : Rule Passed ? :  false

This should not happen, right ?

**Comment by nikunjy** [comment]
You are missing quotes in your rule 
it should be 
`bankcode eq "CIT"`
that is because CIT is a string

Check this out, I modified test.json and rules.txt for your test 
diff --git a/rules.txt b/rules.txt
index 7b2514f..a91de06 100644
--- a/rules.txt
+++ b/rules.txt
@@ -1 +1 @@
-name == "myname" and x.y.b == 2
+bankcode eq "CIT"
diff --git a/test.json b/test.json
index d1e2eb3..f7d9078 100644
--- a/test.json
+++ b/test.json
@@ -1,12 +1,4 @@
 {
-    "x": {
-        "y": {
-            "a": 50,
-            "b": 2
-        },
-        "z": "s"
-    },
-    "name": "myname",
-    "age": 15
+ "bankcode": "CIT"
 }



and I get 
```
 %                                                                                                                                                                                                                                                                               go run main.go
		Rule: bankcode eq "CIT"

		Object: map[bankcode:CIT]
		Answer: true
```

**Comment by nikunjy** [comment]
Please share any advice on the documentation, also feel free to make a pull request :)

**Comment by nikunjy** [comment]
I have changed the root package and now there is an evaluate method in. I also wrote a test and it throws an error for case like yours. You can write your code like the test here 
https://github.com/nikunjy/rules/blob/master/evaluate_test.go#L9
